name: Security Scan

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # Checkout code
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------
      # Setup Node.js
      # ------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ------------------------
      # Install dependencies
      # ------------------------
      - name: Install dependencies
        run: npm install

      # ------------------------
      # Start Express App
      # ------------------------
      - name: Start application
        run: |
          node src/server.js &
          sleep 5

      # ------------------------
      # Install Snyk CLI
      # ------------------------
      - name: Install Snyk CLI
        run: |
          curl --compressed https://downloads.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      # ------------------------
      # Authenticate Snyk
      # ------------------------
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # ------------------------
      # Run Snyk test
      # ------------------------
      - name: Run Snyk test
        run: snyk test || true

      # ------------------------
      # Pull OWASP ZAP image
      # ------------------------
      - name: Pull OWASP ZAP image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      # ------------------------
      # Run ZAP Baseline Scan
      # ------------------------
      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            --network="host" \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:3000 \
            -r report.html \
            -I

      # ------------------------
      # Upload ZAP Report
      # ------------------------
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
